name: Build Next.js Static Export

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Construir la app
        run: npm run build

      - name: Exportar a HTML estático
        run: npm run export

      - name: Subir artefacto (out/)
        uses: actions/upload-artifact@v3
        with:
          name: out
          path: out
